### ISSUE TITLE
Create instance of Aspect::Base and apply to multiple targets(classes/instances)

### ISSUE THREAD

**Issue by gcao** [gcao/aspector#16]
Then aspect instance can be used like a regular class, have instance variable, methods and can be called from advice logic, e.g.

```ruby
class TestAspect < Aspector::Base
  attr_accessor :call_count

  def initialize
    @call_count = 0
  end

  before aspect_arg: true do |aspect|
    aspect.call_count += 1
  end
end

a = TestAspect.new
a.apply A, method: 'do_a'
a.apply B, methods: %w(do_this do_that)
```

**Comment by mensfeld** [comment]
Closing - once travis is done I will merge this. It required some additional work not to break existing API to much and now instead of accessing aspect directly we will have to use interception_arg instead of aspect_arg and just |interception| interception.aspect - that way we can have access to both interception options and aspect options - so the "default" aspector options API won't be broken
