### ISSUE TITLE
Documentation on DSL keywords and available options?

### ISSUE THREAD

**Issue by edelgado** [gcao/aspector#28]
Hi folks, interesting gem, thanks for sharing. I'm having a hard time understanding how to fully use it tho.

**Is there documentation on the domain-specific language keywords?**
For example, I've seen `default`, `target`, etc.

**And for available options?**
For example, `method`, `methods`, `class_methods`,  `private_methods`, `new_methods_only`, `except`, `method_arg`, `name`, etc.

Thanks! :smile:

**Comment by mensfeld** [comment]
Hey @edelgado - currently there is no good documentation for this gem - there are many examples in /examples/ and many more in specs. 

I won't describe all of them now - because I'm on a holiday ;) but be back in couple of days. Then I can provide you with more details.

Also during my holiday I rewrote almost 100% of the code to make in easier to understand and work with (here's a small example of a new DSL):

```
class ActiveRecordHooks < Aspector::Base
  default private_methods: true

  before method: :initialize, run: :before_method

  before method: :save do |handler|
    puts "Before saving #{self.class.name} instance"
  end

  after method: :save do |handler|
    puts "After saving #{self.class.name} instance"
  end
end
```

**Comment by mensfeld** [comment]
Hey @edelgado - I've added the **Default and apply options** description in README. If you need example usage of given options - as far as I remember all are used in examples and/or specs. If you have any further questions feel free to contact me.

**Comment by edelgado** [comment]
Certainly helpful! Thanks @mensfeld :smile:
