### ISSUE TITLE
Is there a way to remove aspects?

### ISSUE THREAD

**Issue by thedeeno** [gcao/aspector#30]
Loving this gem. Is there a standard way to remove applied aspects? When I'm testing I want to reset my application to a pure state between tests and I'd like to remove all applied aspects as part of that reset.

Thoughts?

Thanks for your work on this!

**Comment by mensfeld** [comment]
Hey, @thedeeno, thanks for the support! :)

You cannot unbind the whole aspector, however you can always disable all the aspects that you don't need / don't want:

```ruby
aspect.apply(ExampleClass)
element = ExampleClass.new
element.test
aspect.disable!
element.test

# Expected output
# do_this
# do_that
# test
# test
```

and you can reenable it later. Aspector heavily integrates with given methods but if disabled - won't run at all (no aspector logic except a single check will be performed).

**Comment by thedeeno** [comment]
Do you think it's dangerous to blow away the `self.class.storage` for target's? I'm imagining an implementation that saves a list of constants with advice applied and a `Aspector#reset!` method that iterates over this list and reset's each constant's storage.

Would that work? Or are we hooking even lower than that?

**Comment by thedeeno** [comment]
I mention that because in my case disabling isn't enough. If possible we need to remove all advice so we effectively have a "pre-aspector" runtime.

**Comment by mensfeld** [comment]
@thedeeno I'm really curious about the case - could you explain why do you need that? :)

Blowing up storage won't help. Storage is used to store information where (and how) a given aspect was applied. It was introduced in order to support multi applying same aspect with different options and to support applying to not yet existing methods (once they are defined, we need to know how to apply aspects to them)

Applied aspect heavily (really heavily) integrates with methods to which it is being applied (it deattaches them, wraps the new logic around (or after/before/etc) and then puts the old logic in place (kinda like prepend in 2.2.0 but with logging logic and some other things that are done different). Resetting is possible, however it won't be as easy as you think due to supporting of resetting multiaspect applied methods/objects. 

I can implement this feature, however it will require some time.

Note that resetting will require a given aspect to be applied again (there won't re unreset or anything like that)

**Comment by thedeeno** [comment]
When testing we want to apply different sets of advice to simulate different configured runtimes. Some environments will have logging, some will have metrics, etc. The way to solve this now is to apply in separate test runs (in their own processes) so we don't pollute the object model cross test. Maybe there's a better way to deal with this?

I think it'd be awesome if this library supported at least global reset or perhaps even target-level resets. Applying/removing advice wouldn't feel so permanent if we could reason about it like that.

Unreset isn't necessary. Cool!

**Comment by mensfeld** [comment]
@thedeeno  I've been looking into this recently and it creates some problems with ordering. Let's say that I have 2 aspects (AA, AB) that I apply. Aspector stores the unbind method (original base for adding aspects) and it could be restored, however when I apply the AA and after that AB and I reset! from AA, the AB aspect will go away as well (because for us the native method is the method from the beginning). But then if I reset the AB, it will restore the AA aspect.

The only solution that I see (at least now) is to make aspects aware of each other and that is a really bad idea (memory consumption, performance, etc). However if you still want to do what you are doing, you could unbind the methods that will be replaced with aspected versions and the overwrite them back again the way you want.

I'm not saying now right now - but it seems that this feature requires a lot of planning and it might turn out that it won't be possible to implement due to memory consumption and performance.

**Comment by mensfeld** [comment]
Deprecated and no longer maintained.
